### ISSUE TITLE
Compression mode mess with <pre>

### ISSUE THREAD

**Issue by biloti** [pronovic/gtml#3]
The compression feature (#compress ON) should ignore the content of pre blocks, so not to mess them.

**Comment by pronovic** [comment]
Hi @biloti , the current implementation is very simple &mdash; other than stripping comments, it doesn't interpolate content at all, and that's a design decision that has been in place for 20 years now.  Besides `<pre>`, there are probably other types of content that shouldn't be compressed, and enhancing `#compress` to be aware of those corner cases is a larger change than I am willing to make at this stage in the project's lifetime.

My opinion is that if `#compress` doesn't work for your situation, then you probably should not use it at all.  Personally, I think `#compress` is a late 1990s solution to a problem that has better solutions today.  For instance, compression at the HTTP server level (to reduce the size of data transmitted to the client) probably solves the same problem that `#compress` was written to solve, and it's also a more general solution.

I won't fix this as a bug.  However, if you know what you want and how to implement it - and you're willing to accept responsibility to maintain it over time - I would accept a PR for a new feature that implements the content-aware behavior that you need.   I'd suggest something like `#smartcompress`, that works like `#compress` but makes the changes you need without risking problems with backwards-compatibility for existing users.

**Comment by biloti** [comment]
Perhaps, instead of an issue this should be a feature request. Unfortunately, I'm not that proficient with Perl. Otherwise, I would be glad to contribute.

**Comment by pronovic** [comment]
My main goal for this repository is to offer somewhere reliable for people to get the code, and a place to report bugs if necessary.  SourceForge just isn't viable for that purpose any more.  However, as a general thing, I'm not planning on implementing any feature requests myself.
